openapi: 3.0.4
info:
  title: Horoscope
  description: Horoscope is a simple tool for getting horoscope data. It returns the horoscope for the day.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/horoscope:
    get:
      summary: Get Horoscope
      description: Horoscope is a simple tool for getting horoscope data. It returns the horoscope for the day.
      operationId: horoscope
      parameters:
      - name: sign
        in: query
        schema:
          type: string
        required: true
        description: The zodiac sign for which you want to get the horoscope (e.g., aries)
        example: aries
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  color: purple
                  compatibility:
                  - leo
                  - sagittarius
                  horoscope: Today, you may feel a strong urge to expand your horizons and explore new opportunities. It's a great time to step out of your comfort zone and try something you've never done before. Trust your intuition and follow your instincts. Remember to stay grounded and maintain a sense of balance in all aspects of your life.
                  luckyNumber: 1
                  luckyTime: 1:00 PM
                  mood: bored
                  sign: aries
                  zodiac:
                    element: fire
                    name: Aries
                    stone: bloodstone
                    symbol: â™ˆ
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
