name: apiverve_horoscope
description: Horoscope is a simple tool for getting horoscope data. It returns the horoscope for the day.
version: 1.1.14
homepage: https://horoscope.apiverve.com?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/horoscope-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
